### ISSUE TITLE
dereference output depends on order of input schemas

### ISSUE THREAD

**Issue by jayvdb** [kstasik/schema-tools#67]
We have a bunch of schemas being included from external files.

If a schema refers to a schema that appears after it, like this, the result is very different ...
```yaml
    SchemaDUsingC:
      $ref: "./schemas/SchemaDUsingC.yaml#/components/schemas/SchemaDUsingC"
    SchemaA:
      $ref: "./schemas/SchemaA.yaml#/components/schemas/SchemaA"
    SchemaBUsingA:
      $ref: "./schemas/SchemaBUsingA.yaml#/components/schemas/SchemaBUsingA"
    SchemaCUsingB:
      $ref: "./schemas/SchemaCUsingB.yaml#/components/schemas/SchemaCUsingB"
```

... to when the schemas are ordered so they always only include prior schemas, like:

```yaml
    SchemaA:
      $ref: "./schemas/SchemaA.yaml#/components/schemas/SchemaA"
    SchemaBUsingA:
      $ref: "./schemas/SchemaBUsingA.yaml#/components/schemas/SchemaBUsingA"
    SchemaCUsingB:
      $ref: "./schemas/SchemaCUsingB.yaml#/components/schemas/SchemaCUsingB"
    SchemaDUsingC:
      $ref: "./schemas/SchemaDUsingC.yaml#/components/schemas/SchemaDUsingC"
```

I can provide more details of the schemas if that helps, and reduce it to a few schemas only to better demonstrate the problem.
We're able to workaround it by carefully ordering the schemas.
